name: Docs Push

on:
  push:
    branches:
      - master
      - docspush

jobs:
  docpush:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          set -ex
          pip install -r dev-requirements.txt
          pip install -r docs/requirements.txt
      - name: Install TorchX
        run: |
          set -ex
          python setup.py develop
      - name: Doc Test
        run: |
          set -ex
          cd docs
          make doctest
      - name: Linkcheck
        run: |
          set -ex
          cd docs
          make linkcheck
      - name: Doc Build
        run: |
          set -ex
          cd docs
          make html
      - name: Papermill
        run: |
          set -ex
          cd docs
          make papermill
      - name: Push
        run: |
          set -ex
          docs/doc_push.sh
